let userName = prompt("Привет! Как тебя зовут?")
alert("О классное имя) " + userName)
let userAge = prompt("Сколько тебе лет? " + userName)
alert("Ты уже взрослый(ая)!")
let userMood = prompt("Как дела, как настроение?)")
alert("Это хорошо!!!")
let userSchool = prompt("А чем ты вообще увлекаешься?)")
alert("Вауууу) Молодец!")
let user = prompt("Какой твой любимый Актёр?")
alert("Мой тоже)")
let userr = prompt("Твоё любимое место для отдыха?")
alert("Я тоже)")
let userrr = prompt("Твоё любимое блюдо?")
alert("А я люблю роллы)")
